# Generated by Django 5.2.4 on 2025-07-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Addresses"},
        ),
    ]
